const API='https://loot-market.c-media-satoru.workers.dev';
const GAME={maxHp:30,pHeal:7,pRate:.14};
const RARITY={1:'COMMON',2:'UNCOMMON',3:'RARE',4:'EPIC',5:'LEGENDARY'};
const DIE=['','⚀','⚁','⚂','⚃','⚄','⚅'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
let catalog=[],selectedStage=null,allItems=[],itemMap=new Map(),tab='d',mission,run,enemy,ehp,isBoss=false,bossQ=false,locked=false;
let mem={d:new Set(),w:new Set(),o:new Set()};
try{['d','w','o'].forEach(k=>mem[k]=new Set(JSON.parse(localStorage.getItem('loot-'+k)||'[]')))}catch(e){}
function save(){try{['d','w','o'].forEach(k=>localStorage.setItem('loot-'+k,JSON.stringify([...mem[k]])))}catch(e){}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(v){const raw=String(v??'').trim();if(!raw)return'';try{const u=new URL(raw,location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function mediaUrl(key){return key?`${API}/api/media/${String(key).split('/').map(encodeURIComponent).join('/')}`:''}
function imgSrc(obj){return safeUrl(obj?.image_url)||mediaUrl(obj?.image_key)||''}
function rank(n){return Number(n)||1}
function stars(n){n=Math.max(0,Math.min(5,Number(n)||0));return'★'.repeat(n)+'☆'.repeat(5-n)}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function weightedPick(rows,weightKey){const valid=(rows||[]).filter(Boolean);if(!valid.length)return null;const weights=valid.map(r=>Math.max(0,Number(r[weightKey])||0)),total=weights.reduce((a,b)=>a+b,0);if(total<=0)return pick(valid);let n=Math.random()*total;for(let i=0;i<valid.length;i++){n-=weights[i];if(n<=0)return valid[i]}return valid[valid.length-1]}
function item(id){return itemMap.get(id)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');$('#collectionArea').classList.toggle('hide',id==='#battle');scrollTo(0,0)}
function setArena(id){['enemyState','diceState','skillState','defeatState','lootState','potionState','warningState'].forEach(x=>$('#'+x).classList.toggle('on',x===id))}
function renderStageList(){const root=$('#stageList');if(!catalog.length){root.innerHTML='<div class="empty">公開中のステージがありません。</div>';return}root.innerHTML=catalog.map((s,i)=>{const pic=imgSrc(s),ready=(s.enemies?.length&&s.bosses?.length&&s.items?.length&&s.conditions?.length);return `<div class="card">${pic?`<div class="stagePic"><img src="${esc(pic)}" alt=""></div>`:'<div class="stagePic">🗺️</div>'}<div class="k">STAGE ${String(i+1).padStart(2,'0')}</div><div class="title">${esc(s.name)}</div><div class="sub">${esc(s.description||'')}</div><div class="stageMeta"><span class="tiny">敵 ${s.enemies?.length||0}</span><span class="tiny">ボス ${s.bosses?.length||0}</span><span class="tiny">戦利品 ${s.items?.length||0}</span></div><button class="btn stageSelect" data-id="${esc(s.id)}" ${ready?'':'disabled'}>${ready?'このダンジョンへ':'準備中'}</button></div>`}).join('');$$('.stageSelect').forEach(b=>b.onclick=()=>selectStage(b.dataset.id))}
function render(){bookBadge.textContent='図鑑 '+mem.d.size+' / '+allItems.length;let arr=[...mem[tab]].map(item).filter(Boolean);collection.innerHTML=arr.length?arr.map(x=>{const src=imgSrc(x);return `<div class="mini"><div class="miniPic">${src?`<img src="${esc(src)}" alt="">`:'📦'}</div><div class="miniBody">${esc(x.name)}<div class="sub">${RARITY[rank(x.rarity)]||'UNKNOWN'} / 意味不明★${Number(x.weirdness)||0}</div></div></div>`}).join(''):'<div class="empty">まだ何もない。</div>'}
async function loadCatalog(){try{const res=await fetch(API+'/api/catalog',{cache:'no-store'});const j=await res.json();if(!res.ok||!j.ok)throw new Error(j.error||('HTTP '+res.status));catalog=j.data||[];allItems=catalog.flatMap(s=>s.items||[]);itemMap=new Map(allItems.map(x=>[x.id,x]));try{localStorage.setItem('loot-catalog-cache',JSON.stringify({at:Date.now(),data:catalog}))}catch{}renderStageList();render()}catch(err){let cached=null;try{cached=JSON.parse(localStorage.getItem('loot-catalog-cache')||'null')}catch{}if(cached?.data?.length){catalog=cached.data;allItems=catalog.flatMap(s=>s.items||[]);itemMap=new Map(allItems.map(x=>[x.id,x]));renderStageList();render();$('#stageList').insertAdjacentHTML('afterbegin','<div class="errorBox">通信できないため、前回取得したデータで表示しています。</div>')}else{$('#stageList').innerHTML=`<div class="errorBox">ゲームデータを取得できませんでした。<br>${esc(err.message)}<button class="btn2" id="retryLoad">再読み込み</button></div>`;$('#retryLoad').onclick=loadCatalog}}}
function selectStage(id){selectedStage=catalog.find(s=>s.id===id);if(!selectedStage)return;const i=catalog.indexOf(selectedStage);$('#briefStageNo').textContent='STAGE '+String(i+1).padStart(2,'0');$('#briefTitle').textContent=selectedStage.name;$('#briefDesc').textContent=selectedStage.description||'';const bg=imgSrc(selectedStage);$('#battleShell').style.setProperty('--stage-bg',bg?`url("${bg.replace(/["\\]/g,'')}")`:'none');pMission();show('#brief')}
function pMission(){mission=pick(selectedStage.conditions||[]);$('#briefMission').textContent=mission?.label||'ボス条件がありません'}
function start(){if(!selectedStage||!mission)return;run={hp:GAME.maxHp,kills:0,loot:[],pots:0,boss:null,history:[],powerTurns:0,enemyRolls:0};bossQ=false;isBoss=false;updateComboHud();show('#battle');spawn()}
function renderEnemyVisual(row){const src=imgSrc(row);const box=$('#sprite');box.classList.toggle('boss',isBoss);box.innerHTML=src?`<img src="${esc(src)}" alt="">`:(row?.is_rare?'👁️':isBoss?'👹':'👾')}
function spawn(){isBoss=bossQ;if(isBoss){enemy=run.boss}else{enemy=weightedPick(selectedStage.enemies||[],'spawn_weight')}if(!enemy){gameError('出現できる敵がいません');return}run.enemyRolls=0;ehp=Number(enemy.hp);renderEnemyVisual(enemy);$('#ename').textContent=enemy.name;$('#etag').textContent=isBoss?(Number(enemy.is_rare)?'RARE BOSS':'BOSS'):'ZAKO';$('#ehpL').textContent=isBoss?'BOSS HP':'ENEMY HP';$('#msg').textContent=isBoss?'ボスが出現した。決戦だ。':enemy.name+' が現れた。サイコロを振れ。';setArena('enemyState');$('#enemyState').className='state enemyState on enemyIn';setTimeout(()=>$('#enemyState').className='state enemyState on',320);locked=false;$('#roll').disabled=false;ui()}
function progress(){const u=[...new Set(run.loot)].map(item).filter(Boolean);switch(mission?.type){case'weird':return u.filter(x=>Number(x.weirdness)===5).length;case'rare':return u.filter(x=>rank(x.rarity)>=3).length;case'gift':return u.filter(x=>Number(x.gift_power)===5).length;case'kill':return run.kills;case'uncommon':return u.filter(x=>rank(x.rarity)>=2).length;default:return 0}}
function ui(){if(!run||!enemy)return;$('#phpT').textContent=Math.max(0,run.hp)+' / '+GAME.maxHp;$('#phpB').style.width=Math.max(0,run.hp)/GAME.maxHp*100+'%';$('#ehpT').textContent=Math.max(0,ehp)+' / '+enemy.hp;$('#ehpB').style.width=Math.max(0,ehp)/enemy.hp*100+'%';let p=Math.min(Number(mission.target_value)||1,progress());$('#progT').textContent=p+' / '+mission.target_value;$('#progB').style.width=p/mission.target_value*100+'%';$('#missionT').textContent=mission.label;$('#kills').textContent='撃破 '+run.kills;$('#loots').textContent='戦利品 '+run.loot.length;$('#pots').textContent='ポーション '+run.pots;updateComboHud()}
function updateComboHud(){if(!run)return;const recent=run.history.slice(-3);const chips=[];for(let i=0;i<3;i++){if(i<recent.length)chips.push(`<span class="historyChip">${DIE[recent[i]]} ${recent[i]}</span>`);else chips.push('<span class="historyChip">?</span>')}$('#diceHistory').innerHTML=chips.join('<span class="historyArrow">→</span>');$('#powerStatus').classList.toggle('hide',run.powerTurns<=0);$('#powerStatus').textContent=run.powerTurns>0?`POWER ×2　残り ${run.powerTurns}`:''}
function historyEnds(seq){if(run.history.length<seq.length)return false;const tail=run.history.slice(-seq.length);return seq.every((n,i)=>tail[i]===n)}
function detectSequenceSkill(){if(historyEnds([1,1]))return'rescue';if(historyEnds([6,6]))return'beloved';if(historyEnds([1,2,3]))return'blessing';if(historyEnds([4,5,6]))return'theory';return null}
function consumePower(base){const boosted=run.powerTurns>0;const damage=boosted?base*2:base;if(boosted)run.powerTurns--;updateComboHud();return{damage,boosted}}
async function showSingleRoll(final){setArena('diceState');$('#diceState').innerHTML=`<div class="diceStage"><div class="diceCaption">ROLLING...</div><div class="diceRack"><div class="dieVisual spinning" id="liveDie">${DIE[ri(1,6)]}</div></div><div class="rollText">運命を決めろ。</div></div>`;const live=$('#liveDie');const timer=setInterval(()=>{live.textContent=DIE[ri(1,6)]},80);await wait(720);clearInterval(timer);live.classList.remove('spinning');live.textContent=DIE[final];$('#diceState').innerHTML=`<div class="diceStage"><div class="diceCaption">DICE RESULT</div><div class="diceRack"><div class="dieVisual">${DIE[final]}</div></div><div class="rollNumber ${final>=5?'high':final===1?'low':''}">${final}</div><div class="rollText">${final===6?'MAX ROLL!':final===1?'最低の一撃。だが、まだ分からない。':'攻撃力 '+final}</div></div>`;await wait(620)}
async function showMultiRoll(count,label){const values=Array.from({length:count},()=>ri(1,6));setArena('diceState');$('#diceState').innerHTML=`<div class="diceStage"><div class="diceCaption">${esc(label)}</div><div class="diceRack multi">${Array.from({length:count},(_,i)=>`<div class="dieVisual spinning" data-i="${i}">${DIE[ri(1,6)]}</div>`).join('')}</div><div class="rollText">複数の骰子が同時に落ちる。</div></div>`;const timer=setInterval(()=>{$$('#diceState .dieVisual').forEach(d=>d.textContent=DIE[ri(1,6)])},80);await wait(820);clearInterval(timer);$$('#diceState .dieVisual').forEach((d,i)=>{d.classList.remove('spinning');d.textContent=DIE[values[i]]});const sum=values.reduce((a,b)=>a+b,0);$('#diceState').insertAdjacentHTML('beforeend',`<div class="sumLine">${values.join(' + ')} = ${sum}</div>`);await wait(680);return{values,sum}}
async function showSkill(type){const data={rescue:{mark:'✦',name:'神の救済',desc:'絶望の底に、三つの骰子が降りる。',cls:'divine'},beloved:{mark:'♛',name:'神に愛されし者',desc:'祝福された二つの骰子が、追撃を告げる。',cls:'rareSkill'},blessing:{mark:'✧',name:'女神の祝福',desc:'生命の光が満ちる。HPを完全回復。',cls:'heal'},theory:{mark:'⚔',name:'強者の理論',desc:'次の3回の攻撃ダメージが2倍になる。',cls:'rage'},first:{mark:'⚡',name:'先手必勝',desc:'初撃で流れを奪った。反撃前にもう一度攻撃できる。',cls:''}}[type];setArena('skillState');$('#skillState').innerHTML=`<div class="skillPanel ${data.cls}"><div class="skillMark">${data.mark}</div><div class="skillMini">SKILL ACTIVATED</div><div class="skillName">${data.name}</div><div class="skillDesc">${data.desc}</div></div>`;await wait(1100)}
async function applyPlayerDamage(base,label='攻撃'){const result=consumePower(base);ehp-=result.damage;setArena('enemyState');$('#enemyState').className='state enemyState on enemyHit';$('#msg').textContent=`${label} ${result.damage}ダメージ${result.boosted?'！ POWER ×2':''}`;ui();await wait(330);$('#enemyState').className='state enemyState on';return result.damage}
async function resolveSequenceSkill(type){if(!type)return;if(type==='blessing'){await showSkill('blessing');run.hp=GAME.maxHp;ui();$('#msg').textContent='女神の祝福。HPが全回復した。';await wait(380);return}if(type==='theory'){await showSkill('theory');run.powerTurns=3;updateComboHud();$('#msg').textContent='強者の理論。次の3回、攻撃力2倍。';await wait(380);return}if(ehp<=0)return;if(type==='rescue'){await showSkill('rescue');const r=await showMultiRoll(3,'DIVINE TRIPLE ROLL');await applyPlayerDamage(r.sum,'神の救済');return}if(type==='beloved'){await showSkill('beloved');const r=await showMultiRoll(2,'BLESSED DOUBLE ROLL');await applyPlayerDamage(r.sum,'神に愛されし者');}}
async function rollDice(){if(locked||run.hp<=0||ehp<=0)return;locked=true;$('#roll').disabled=true;const firstAttack=run.enemyRolls===0;run.enemyRolls++;const n=ri(1,6);await showSingleRoll(n);run.history.push(n);if(run.history.length>12)run.history.shift();updateComboHud();const sequenceSkill=detectSequenceSkill();await applyPlayerDamage(n,`🎲 ${n}`);if(sequenceSkill)await resolveSequenceSkill(sequenceSkill);if(ehp<=0){$('#msg').textContent=`${enemy.name} を撃破！`;ui();await wait(420);showDefeat();return}if(firstAttack&&n>=5){await showSkill('first');$('#msg').textContent='先手必勝！ 反撃前にもう一度振れる。';setArena('enemyState');locked=false;$('#roll').disabled=false;ui();return}await wait(260);const d=ri(Number(enemy.attack_min),Number(enemy.attack_max));run.hp-=d;$('#msg').textContent=`敵の反撃。${d}ダメージ。`;ui();await wait(420);if(run.hp<=0){gameOver();return}setArena('enemyState');locked=false;$('#roll').disabled=false}
function showDefeat(){$('#defeatSub').textContent=isBoss?'ボスを撃破した':'敵を撃破した';setArena('defeatState');setTimeout(win,650)}
function dropItem(min=1){let pool=(selectedStage.items||[]).filter(x=>rank(x.rarity)>=min&&!run.loot.includes(x.id));if(!pool.length)pool=(selectedStage.items||[]).filter(x=>rank(x.rarity)>=min);if(!pool.length)pool=selectedStage.items||[];return pool.length?pick(pool):null}
function win(){if(isBoss){const loot=dropItem(Number(enemy.min_loot_rarity)||3);if(!loot){clearStage();return}showLoot(loot,true);return}run.kills++;if(Math.random()<GAME.pRate){run.pots++;let b=run.hp;run.hp=Math.min(GAME.maxHp,run.hp+GAME.pHeal);showPotion(run.hp-b)}else{const loot=dropItem();if(loot)showLoot(loot,false);else cont()}ui()}
function showPotion(h){$('#potionState').innerHTML=`<div class="potionIcon">🧪</div><div class="potionTitle">回復ポーション</div><div class="potionText">HPを ${h} 回復した。</div><button class="btn2" id="nextPotion">次へ</button>`;setArena('potionState');$('#nextPotion').onclick=cont;$('#msg').textContent='ポーションを入手。'}
function showLoot(x,boss){run.loot.push(x.id);mem.d.add(x.id);save();render();const src=imgSrc(x),shop=safeUrl(x.affiliate_url),rarity=RARITY[rank(x.rarity)]||'UNKNOWN';$('#lootState').innerHTML=`<div class="lootCard"><div class="lootTop"><div class="lootIcon">${src?`<img src="${esc(src)}" alt="">`:'📦'}</div><div class="lootInfo"><span class="rar">${rarity}${boss?' ・ BOSS LOOT':''}</span><div class="iname">${esc(x.name)}</div><div class="lootDesc">${esc(x.description||x.category||x.provider||'実在商品')}</div></div></div><div class="metrics"><div class="metric"><small>意味不明</small><strong>${stars(x.weirdness)}</strong></div><div class="metric"><small>実用性</small><strong>${stars(x.usefulness)}</strong></div><div class="metric"><small>プレゼント力</small><strong>${stars(x.gift_power)}</strong></div></div><div class="lootActions"><button class="action ${mem.w.has(x.id)?'on':''}" id="wish">♡ 欲しい</button><button class="action ${mem.o.has(x.id)?'on':''}" id="own">✓ 持ってる</button></div>${shop?`<a class="shopLink" href="${esc(shop)}" target="_blank" rel="nofollow sponsored noopener">実物を見る ↗</a>`:''}<button class="btn2" id="nextLoot">${boss?'クリア結果へ':'次へ'}</button></div>`;setArena('lootState');$('#wish').onclick=()=>tog('w',x.id,$('#wish'));$('#own').onclick=()=>tog('o',x.id,$('#own'));$('#nextLoot').onclick=boss?clearStage:cont;$('#msg').textContent='戦利品を獲得。'}
function chooseBoss(){const bosses=selectedStage.bosses||[];run.boss=weightedPick(bosses,'encounter_rate')||bosses[0]||null;return run.boss}
function showWarning(){const b=chooseBoss();if(!b){gameError('ボスが設定されていません');return}$('#roll').disabled=true;locked=true;let rare=Number(b.is_rare)===1;$('#warningState').innerHTML=rare?`<div class="warningPanel rare"><div class="warningMini">UNIDENTIFIED HOSTILE SIGNAL</div><div class="warningWord">DANGER</div><div class="rareSig">UNKNOWN SIGNAL DETECTED</div><div class="warningBody">通常個体とは異なる反応を検知。<br>識別不能な敵性存在が接近しています。</div><div class="warningBoss">RARE BOSS 出現</div><button class="warningBtn" id="warningGo">接触する</button></div>`:`<div class="warningPanel"><div class="warningMini">BOSS ALERT</div><div class="warningWord">WARNING</div><div class="warningBody">ダンジョン内の異常反応を検知。<br>強力な敵性在庫が接近しています。</div><div class="warningBoss">BOSS 出現</div><button class="warningBtn" id="warningGo">ボス戦へ</button></div>`;setArena('warningState');$('#msg').textContent=rare?'識別不能な反応。何かがおかしい。':'警告。ボスが出現する。';$('#warningGo').onclick=spawn}
function tog(k,id,el){mem[k].has(id)?mem[k].delete(id):mem[k].add(id);el.classList.toggle('on',mem[k].has(id));save();render()}
function cont(){if(progress()>=Number(mission.target_value)&&!bossQ){bossQ=true;showWarning();return}spawn()}
function gameOver(){$('#rIco').textContent='💀';$('#rTitle').textContent='GAME OVER';$('#rSub').innerHTML='撃破 '+run.kills+'体 / 戦利品 '+run.loot.length+'個。<br>発見商品は図鑑に残ります。';show('#result')}
function clearStage(){const rare=Number(run.boss?.is_rare)===1;$('#rIco').textContent=rare?'👁️':'🏆';$('#rTitle').textContent=rare?'RARE BOSS CLEAR':'STAGE CLEAR';$('#rSub').innerHTML='撃破 '+run.kills+'体 / 戦利品 '+run.loot.length+'個 / 残りHP '+Math.max(0,run.hp);show('#result')}
function gameError(text){$('#rIco').textContent='⚠️';$('#rTitle').textContent='DATA ERROR';$('#rSub').textContent=text;show('#result')}
$('#back').onclick=()=>show('#stage');$('#enter').onclick=start;$('#roll').onclick=rollDice;$('#retry').onclick=()=>{if(selectedStage){pMission();show('#brief')}else show('#stage')};$('#home').onclick=()=>show('#stage');$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');tab=b.dataset.t;render()});
loadCatalog();
